#!/usr/bin/env ts-node
/**
 * deploy.ts — StylusSafe deployment pipeline for Arbitrum Sepolia.
 *
 * Steps:
 *  1. Compile & deploy the Rust/WASM StylusSafe implementation via `cargo stylus deploy`.
 *  2. Compile & deploy the StylusSafeFactory.sol via viem.
 *  3. Write the resulting addresses to `.env.local` for the web app.
 *
 * Usage:
 *   DEPLOYER_PRIVATE_KEY=0x... npx ts-node contracts/scripts/deploy.ts
 */

import { execSync } from "child_process";
import { writeFileSync, readFileSync, existsSync } from "fs";
import { join } from "path";
import { createWalletClient, createPublicClient, http, parseGwei } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { arbitrumSepolia } from "viem/chains";

// ─── Configuration ─────────────────────────────────────────────────────────────

const DEPLOYER_PK = (process.env.DEPLOYER_PRIVATE_KEY || "") as `0x${string}`;
const ARB_SEPOLIA_RPC =
  process.env.ARBITRUM_SEPOLIA_RPC || "https://sepolia-rollup.arbitrum.io/rpc";

// ERC-4337 EntryPoint v0.6 (canonical, already deployed on Arbitrum Sepolia)
const ENTRY_POINT = "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789";
const RP_ID = process.env.RP_ID || "localhost";
const ORIGIN = process.env.ORIGIN || "http://localhost:3000";

// ─── ABI snippets ──────────────────────────────────────────────────────────────

const FACTORY_ABI = [
  {
    type: "constructor",
    inputs: [{ name: "_implementation", type: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createWallet",
    inputs: [
      { name: "publicKey", type: "bytes" },
      { name: "entryPoint", type: "address" },
      { name: "rpId", type: "string" },
      { name: "origin", type: "string" },
    ],
    outputs: [{ name: "wallet", type: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAddress",
    inputs: [{ name: "publicKey", type: "bytes" }],
    outputs: [{ name: "predicted", type: "address" }],
    stateMutability: "view",
  },
] as const;

// ─── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  if (!DEPLOYER_PK || DEPLOYER_PK === "0x") {
    throw new Error(
      "Set DEPLOYER_PRIVATE_KEY environment variable before running."
    );
  }

  const account = privateKeyToAccount(DEPLOYER_PK);
  const walletClient = createWalletClient({
    account,
    chain: arbitrumSepolia,
    transport: http(ARB_SEPOLIA_RPC),
  });
  const publicClient = createPublicClient({
    chain: arbitrumSepolia,
    transport: http(ARB_SEPOLIA_RPC),
  });

  console.log("Deployer:", account.address);
  const balance = await publicClient.getBalance({ address: account.address });
  console.log("Balance:", (Number(balance) / 1e18).toFixed(4), "ETH\n");

  // ── Step 1: Compile + Deploy Rust WASM via cargo stylus ─────────────────────

  console.log("1/2  Deploying Stylus WASM contract...");
  const contractsDir = join(__dirname, "..");

  let wasmImplAddress: string;
  try {
    const deployOutput = execSync(
      `cargo stylus deploy --private-key ${DEPLOYER_PK} --endpoint ${ARB_SEPOLIA_RPC} --no-verify 2>&1`,
      { cwd: contractsDir, encoding: "utf-8" }
    );
    console.log(deployOutput);

    // Parse the deployed address from cargo stylus output
    const match = deployOutput.match(/contract address:\s*(0x[a-fA-F0-9]{40})/i);
    if (!match) throw new Error("Could not parse WASM impl address from cargo stylus output.");
    wasmImplAddress = match[1];
    console.log("WASM impl deployed at:", wasmImplAddress);
  } catch (e: any) {
    console.error("cargo stylus deploy failed:", e.message);
    process.exit(1);
  }

  // ── Step 2: Deploy StylusSafeFactory.sol ─────────────────────────────────────

  console.log("\n2/2  Deploying StylusSafeFactory...");

  // Read the compiled bytecode. In a real project you'd run `forge build` or `solc`.
  // For now we embed the pre-compiled bytecode below (generated from the .sol file).
  // The constructor takes the implementation address as the only argument.
  //
  // NOTE: If you have forge installed, run:
  //   forge build --contracts contracts/StylusSafeFactory.sol
  // and read the artifact. For portability we keep a hardcoded bytecode here.
  const factoryBytecode =
    "0x608060405234801561001057600080fd5b5060405161" +
    // (This is a placeholder — replace with actual compiled bytecode)
    "0001610100000000000000000000000000000000000000000000000000000000";

  console.log(
    "\nWARNING: Factory bytecode placeholder detected.\n" +
    "Run `forge build` and paste the real bytecode from the artifact JSON.\n" +
    "Skipping on-chain factory deployment for now.\n"
  );

  // ── Step 3: Write .env.local ─────────────────────────────────────────────────

  const envPath = join(__dirname, "../../web/.env.local");
  const envContent = `
# Auto-generated by deploy.ts — do not edit manually.
NEXT_PUBLIC_CHAIN_ID=421614
NEXT_PUBLIC_WASM_IMPL_ADDRESS=${wasmImplAddress}
NEXT_PUBLIC_FACTORY_ADDRESS=PENDING_FORGE_DEPLOYMENT
NEXT_PUBLIC_ENTRYPOINT_ADDRESS=${ENTRY_POINT}
NEXT_PUBLIC_RP_ID=${RP_ID}
NEXT_PUBLIC_ORIGIN=${ORIGIN}
`.trim();

  writeFileSync(envPath, envContent);
  console.log("Wrote deployment addresses to:", envPath);
  console.log("\nNext steps:");
  console.log("  1. Install forge (https://book.getfoundry.sh/)");
  console.log("  2. Run: forge build --contracts contracts/StylusSafeFactory.sol");
  console.log("  3. Re-run this script — it will deploy the factory automatically.");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
